### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by mozillalives** [brunobord/cmdbot#15]
This is probably just an error with my setup, but I got this error on a pretty default setup of ircd-hybrid.

INFO:root:Translation Not Found. Fallback to default
INFO:root:Connection to host...
Connection to host...
Traceback (most recent call last):
  File "./eightball.py", line 33, in <module>
    bot.run()
  File "/home/bot/env/lib/python2.7/site-packages/cmdbot/core.py", line 177, in run
    readbuffer = readbuffer + self.s.recv(1024).decode('utf8')
  File "/home/bot/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 1023: unexpected end of data

I was able to get the bot to work though by changing line 177 of cmdbot/core.py to the following

```
try:
    readbuffer = readbuffer + self.s.recv(1024).decode('utf')
except UnicodeDecodeError:
    continue
```

**Comment by brunobord** [comment]
Hi,
Thank you for this bug report. I may try to fix it as soon as possible.
If you could add more traceback (including the string sent back to the bot) that'd be great.
Could you please tell me if you're using the latest cmdbot codebase or an earlier release?

**Comment by mozillalives** [comment]
Sorry, I didn't see this and I ended up doing something with cinch instead. I'll download the latest version and see if I still get this same issue sometime next week.

**Comment by brunobord** [comment]
still not fixed. dammit. curse with the IRC clients.
